#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("m2m.Android.Resource", IsApplication=true)]

namespace m2m.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::m2m.Android.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::m2m.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int car_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000b
			public const int City = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int Image = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int LastSeen = 2131099666;
			
			// aapt resource value: 0x7f060004
			public const int LocationTextView = 2131099652;
			
			// aapt resource value: 0x7f06000d
			public const int Navigation_Title = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int State = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int Status = 2131099665;
			
			// aapt resource value: 0x7f06000a
			public const int Street = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int Text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int ThingName = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int latitude = 2131099656;
			
			// aapt resource value: 0x7f060003
			public const int listView = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int login = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int longiude = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int password = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int properties = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int propertyName = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int unit = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int username = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_properties_list = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_thing = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_things_list = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list_cell_Property = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int listcell_thing = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int location_details = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int nav_bar = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int thing_brief_description = 2130903049;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040003
			public const int ApplicationName = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Hello = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
